#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

~/.screenlayout/layout.sh

$HOME/.config/polybar/launch.sh
picom &
feh --bg-fill ~/Pictures/wallpaper9.png

# MPD daemon start (if no other user instance exists)
[ ! -s ~/.config/mpd/pid ] && mpd && mpc pause &

bspc monitor HDMI1 -d I II III IV V
bspc monitor eDP1 -d VI VII VIII IX X

bspc config border_width        0
bspc config window_gap          24

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config bottom_padding 0
bspc config top_padding 60
